#Travis-ci config file

sudo: required
dist: trusty


services:
  - docker
  - memcached

before_install:
  - docker build -t stonemason .
  - docker pull memcached
  - docker run -d -p 127.0.0.1:11211:11211 --name memcache memcached

script:
  - docker run  -v `pwd`:/tmp/ --workdir /tmp/ --link memcache:localhost --entrypoint python3.5 stonemason -m tox

notifications:
  email:
    recipients:
      - gliese.q@gmail.com
      - kotaimen.c@gmail.com

