#Travis-ci config file

sudo: required
dist: trusty


services:
  - docker

before_install:
  - docker build -t stonemason .
  - docker pull memcached
  - docker run -d --name memcache memcached-alpine

script:
  - docker run --rm -v `pwd`:/tmp/ --workdir /tmp/ --link memcache:localhost --entrypoint python3 stonemason -m tox

notifications:
  email:
    recipients:
      - gliese.q@gmail.com
      - kotaimen.c@gmail.com

